"""
Define the Countries model
"""
from enum import Enum


class Countries(Enum):
    AF = 'Afghanistan'
    AL = 'Albania'
    DZ = 'Algeria'
    AD = 'Andorra'
    AO = 'Angola'
    AG = 'Antigua and Barbuda'
    AR = 'Argentina'
    AM = 'Armenia'
    AU = 'Australia'
    AT = 'Austria'
    AZ = 'Azerbaijan'
    BS = 'Bahamas'
    BH = 'Bahrain'
    BD = 'Bangladesh'
    BB = 'Barbados'
    BY = 'Belarus'
    BE = 'Belgium'
    BZ = 'Belize'
    BJ = 'Benin'
    BT = 'Bhutan'
    BO = 'Bolivia'
    BA = 'Bosnia and Herzegovina'
    BW = 'Botswana'
    BR = 'Brazil'
    BN = 'Brunei'
    BG = 'Bulgaria'
    BF = 'Burkina Faso'
    BI = 'Burundi'
    KH = 'Cambodia'
    CM = 'Cameroon'
    CA = 'Canada'
    CV = 'Cape Verde'
    CF = 'Central African Republic'
    TD = 'Chad'
    CL = 'Chile'
    CN = 'China'
    CO = 'Colombia'
    KM = 'Comoros'
    CG = 'Congo'
    CR = 'Costa Rica'
    HR = 'Croatia'
    CU = 'Cuba'
    CY = 'Cyprus'
    CZ = 'Czech Republic'
    DK = 'Denmark'
    DJ = 'Djibouti'
    DM = 'Dominica'
    DO = 'Dominican Republic'
    EC = 'Ecuador'
    EG = 'Egypt'
    SV = 'El Salvador'
    GQ = 'Equatorial Guinea'
    ER = 'Eritrea'
    EE = 'Estonia'
    ET = 'Ethiopia'
    FJ = 'Fiji'
    FI = 'Finland'
    FR = 'France'
    GA = 'Gabon'
    GM = 'Gambia'
    GE = 'Georgia'
    DE = 'Germany'
    GH = 'Ghana'
    GR = 'Greece'
    GD = 'Grenada'
    GT = 'Guatemala'
    GN = 'Guinea'
    GW = 'Guinea-Bissau'
    GY = 'Guyana'
    HT = 'Haiti'
    HN = 'Honduras'
    HU = 'Hungary'
    IS = 'Iceland'
    IN = 'India'
    ID = 'Indonesia'
    IR = 'Iran'
    IQ = 'Iraq'
    IE = 'Ireland'
    IL = 'Israel'
    IT = 'Italy'
    JM = 'Jamaica'
    JP = 'Japan'
    JO = 'Jordan'
    KZ = 'Kazakhstan'
    KE = 'Kenya'
    KI = 'Kiribati'
    KP = 'North Korea'
    KR = 'South Korea'
    KW = 'Kuwait'
    KG = 'Kyrgyzstan'
    LA = 'Laos'
    LV = 'Latvia'
    LB = 'Lebanon'
    LS = 'Lesotho'
    LR = 'Liberia'
    LY = 'Libya'
    LI = 'Liechtenstein'
    LT = 'Lithuania'
    LU = 'Luxembourg'
    MK = 'North Macedonia'
    MG = 'Madagascar'
    MW = 'Malawi'
    MY = 'Malaysia'
    MV = 'Maldives'
    ML = 'Mali'
    MT = 'Malta'
    MH = 'Marshall Islands'
    MR = 'Mauritania'
    MU = 'Mauritius'
    MX = 'Mexico'
    FM = 'Micronesia'
    MD = 'Moldova'
    MC = 'Monaco'
    MN = 'Mongolia'
    ME = 'Montenegro'
    MA = 'Morocco'
    MZ = 'Mozambique'
    MM = 'Myanmar'
    NA = 'Namibia'
    NR = 'Nauru'
    NP = 'Nepal'
    NL = 'Netherlands'
    NZ = 'New Zealand'
    NI = 'Nicaragua'
    NE = 'Niger'
    NG = 'Nigeria'
    NO = 'Norway'
    OM = 'Oman'
    PK = 'Pakistan'
    PW = 'Palau'
    PA = 'Panama'
    PG = 'Papua New Guinea'
    PY = 'Paraguay'
    PE = 'Peru'
    PH = 'Philippines'
    PL = 'Poland'
    PT = 'Portugal'
    QA = 'Qatar'
    RO = 'Romania'
    RU = 'Russia'
    RW = 'Rwanda'
    KN = 'Saint Kitts and Nevis'
    LC = 'Saint Lucia'
    VC = 'Saint Vincent and the Grenadines'
    WS = 'Samoa'
    SM = 'San Marino'
    ST = 'Sao Tome and Principe'
    SA = 'Saudi Arabia'
    SN = 'Senegal'
    RS = 'Serbia'
    SC = 'Seychelles'
    SL = 'Sierra Leone'
    SG = 'Singapore'
    SK = 'Slovakia'
    SI = 'Slovenia'
    SB = 'Solomon Islands'
    SO = 'Somalia'
    ZA = 'South Africa'
    SS = 'South Sudan'
    ES = 'Spain'
    LK = 'Sri Lanka'
    SD = 'Sudan'
    SR = 'Suriname'
    SZ = 'Eswatini'
    SE = 'Sweden'
    CH = 'Switzerland'
    SY = 'Syria'
    TJ = 'Tajikistan'
    TZ = 'Tanzania'
    TH = 'Thailand'
    TL = 'Timor-Leste'
    TG = 'Togo'
    TO = 'Tonga'
    TT = 'Trinidad and Tobago'
    TN = 'Tunisia'
    TR = 'Turkey'
    TM = 'Turkmenistan'
    TV = 'Tuvalu'
    UG = 'Uganda'
    UA = 'Ukraine'
    AE = 'United Arab Emirates'
    GB = 'United Kingdom'
    US = 'United States'
    UY = 'Uruguay'
    UZ = 'Uzbekistan'
    VU = 'Vanuatu'
    VA = 'Vatican City'
    VE = 'Venezuela'
    VN = 'Vietnam'
    YE = 'Yemen'
    ZM = 'Zambia'
    ZW = 'Zimbabwe'

    def all(self):
        countries = [self.AF, self.AL, self.DZ, self.AD, self.AO, self.AG, self.AR, self.AM, self.AU, self.AT, self.AZ,
                     self.BS, self.BH, self.BD, self.BB, self.BY, self.BE, self.BZ, self.BJ, self.BT, self.BO, self.BA,
                     self.BW, self.BR, self.BN,
                     self.BG,
                     self.BF, self.BI, self.KH, self.CM, self.CA, self.CV, self.CF, self.TD, self.CL, self.CN, self.CO,
                     self.KM, self.CG, self.CR, self.HR, self.CU, self.CY, self.CZ, self.DK, self.DJ, self.DM, self.DO,
                     self.EC, self.EG, self.SV,
                     self.GQ,
                     self.ER, self.EE, self.ET, self.FJ, self.FI, self.FR, self.GA, self.GM, self.GE, self.DE, self.GH,
                     self.GR, self.GD, self.GT, self.GN, self.GW, self.GY, self.HT, self.HN, self.HU, self.IS, self.IN,
                     self.ID, self.IR, self.IQ,
                     self.IE,
                     self.IL, self.IT, self.JM, self.JP, self.JO, self.KZ, self.KE, self.KI, self.KP, self.KR, self.KW,
                     self.KG, self.LA, self.LV, self.LB, self.LS, self.LR, self.LY, self.LI, self.LT, self.LU, self.MK,
                     self.MG, self.MW, self.MY,
                     self.MV,
                     self.ML, self.MT, self.MH, self.MR, self.MU, self.MX, self.FM, self.MD, self.MC, self.MN, self.ME,
                     self.MA, self.MZ, self.MM, self.NA, self.NR, self.NP, self.NL, self.NZ, self.NI, self.NE, self.NG,
                     self.NO, self.OM, self.PK,
                     self.PW,
                     self.PA, self.PG, self.PY, self.PE, self.PH, self.PL, self.PT, self.QA, self.RO, self.RU, self.RW,
                     self.KN, self.LC, self.VC, self.WS, self.SM, self.ST, self.SA, self.SN, self.RS, self.SC, self.SL,
                     self.SG, self.SK, self.SI,
                     self.SB,
                     self.SO, self.ZA, self.SS, self.ES, self.LK, self.SD, self.SR, self.SZ, self.SE, self.CH, self.SY,
                     self.TJ, self.TZ, self.TH, self.TL, self.TG, self.TO, self.TT, self.TN, self.TR, self.TM, self.TV,
                     self.UG, self.UA, self.AE,
                     self.GB,
                     self.US, self.UY, self.UZ, self.VU, self.VA, self.VE, self.VN, self.YE, self.ZM, self.ZW]

        sorted_countries = sorted(countries)

        for country in sorted_countries:
            print(country)
