"""
Define the Wine Grape Variety dict
"""


class WineGrapeVarieties():

    def all():
        varieties = [
            # Category: Vinho
            {"id": 1001, "main_category_id": 1, "name": "Aglianico"},
            {"id": 1002, "main_category_id": 1, "name": "Aglianico del Vulture"},
            {"id": 1003, "main_category_id": 1, "name": "Alfrocheiro"},
            {"id": 1004, "main_category_id": 1, "name": "Alicante Bouschet"},
            {"id": 1005, "main_category_id": 1, "name": "Alicante Branco"},
            {"id": 1006, "main_category_id": 1, "name": "Alvarelhão"},
            {"id": 1007, "main_category_id": 1, "name": "Alvarelhão-Ceitão"},
            {"id": 1008, "main_category_id": 1, "name": "Alvarinho"},
            {"id": 1009, "main_category_id": 1, "name": "Ancellotta"},
            {"id": 1010, "main_category_id": 1, "name": "Antão Vaz"},
            {"id": 1011, "main_category_id": 1, "name": "Aragonês"},
            {"id": 1012, "main_category_id": 1, "name": "Aramon"},
            {"id": 1013, "main_category_id": 1, "name": "Arinto"},
            {"id": 1014, "main_category_id": 1, "name": "Arinto dos Açores"},
            {"id": 1015, "main_category_id": 1, "name": "Arneis"},
            {"id": 1016, "main_category_id": 1, "name": "Avesso"},
            {"id": 1017, "main_category_id": 1, "name": "Azal Branco"},
            {"id": 1018, "main_category_id": 1, "name": "Baga"},
            {"id": 1019, "main_category_id": 1, "name": "Barbera"},
            {"id": 1020, "main_category_id": 1, "name": "Barcelo"},
            {"id": 1021, "main_category_id": 1, "name": "Bastardo"},
            {"id": 1022, "main_category_id": 1, "name": "Bical"},
            {"id": 1023, "main_category_id": 1, "name": "Boal"},
            {"id": 1024, "main_category_id": 1, "name": "Borraçal"},
            {"id": 1025, "main_category_id": 1, "name": "Cabernet Franc"},
            {"id": 1026, "main_category_id": 1, "name": "Cabernet Sauvignon"},
            {"id": 1027, "main_category_id": 1, "name": "Camarate"},
            {"id": 1028, "main_category_id": 1, "name": "Carignan"},
            {"id": 1029, "main_category_id": 1, "name": "Carménère"},
            {"id": 1030, "main_category_id": 1, "name": "Carricante"},
            {"id": 1031, "main_category_id": 1, "name": "Casculho"},
            {"id": 1032, "main_category_id": 1, "name": "Castelão"},
            {"id": 1033, "main_category_id": 1, "name": "Cerceal"},
            {"id": 1034, "main_category_id": 1, "name": "Cerceal Branco"},
            {"id": 1035, "main_category_id": 1, "name": "Cercial"},
            {"id": 1036, "main_category_id": 1, "name": "Chardonnay"},
            {"id": 1037, "main_category_id": 1, "name": "Chenin Blanc"},
            {"id": 1038, "main_category_id": 1, "name": "Cinsault"},
            {"id": 1039, "main_category_id": 1, "name": "Cornifesto"},
            {"id": 1040, "main_category_id": 1, "name": "Corvina"},
            {"id": 1041, "main_category_id": 1, "name": "Corvinone"},
            {"id": 1042, "main_category_id": 1, "name": "Croatina"},
            {"id": 1043, "main_category_id": 1, "name": "Códega do Larinho"},
            {"id": 1044, "main_category_id": 1, "name": "Diagalves"},
            {"id": 1045, "main_category_id": 1, "name": "Dona Branca"},
            {"id": 1046, "main_category_id": 1, "name": "Donzelinho"},
            {"id": 1047, "main_category_id": 1, "name": "Donzelinho Tinto"},
            {"id": 1048, "main_category_id": 1, "name": "Dozelinho"},
            {"id": 1049, "main_category_id": 1, "name": "Encruzado"},
            {"id": 1050, "main_category_id": 1, "name": "Espadeiro"},
            {"id": 1051, "main_category_id": 1, "name": "Falanghina"},
            {"id": 1052, "main_category_id": 1, "name": "Fernão Pires"},
            {"id": 1053, "main_category_id": 1, "name": "Folgasão"},
            {"id": 1054, "main_category_id": 1, "name": "Fonte Cal"},
            {"id": 1055, "main_category_id": 1, "name": "Furmint"},
            {"id": 1056, "main_category_id": 1, "name": "Galego Dourado"},
            {"id": 1057, "main_category_id": 1, "name": "Garganega"},
            {"id": 1058, "main_category_id": 1, "name": "Garnacha"},
            {"id": 1059, "main_category_id": 1, "name": "Gewürztraminer"},
            {"id": 1060, "main_category_id": 1, "name": "Glera"},
            {"id": 1061, "main_category_id": 1, "name": "Gonçalo Pires"},
            {"id": 1062, "main_category_id": 1, "name": "Gouveio"},
            {"id": 1063, "main_category_id": 1, "name": "Gouveio Real"},
            {"id": 1064, "main_category_id": 1, "name": "Graciano"},
            {"id": 1065, "main_category_id": 1, "name": "Grand Noir"},
            {"id": 1066, "main_category_id": 1, "name": "Grechetto"},
            {"id": 1067, "main_category_id": 1, "name": "Greco di Tufo"},
            {"id": 1068, "main_category_id": 1, "name": "Grenache"},
            {"id": 1069, "main_category_id": 1, "name": "Grenache Branca"},
            {"id": 1070, "main_category_id": 1, "name": "Grillo"},
            {"id": 1071, "main_category_id": 1, "name": "Hárslevelű"},
            {"id": 1072, "main_category_id": 1, "name": "Inzolia"},
            {"id": 1073, "main_category_id": 1, "name": "Jaen"},
            {"id": 1074, "main_category_id": 1, "name": "Jampal"},
            {"id": 1075, "main_category_id": 1, "name": "Kabar"},
            {"id": 1076, "main_category_id": 1, "name": "Lambrusco di Sorbara"},
            {"id": 1077, "main_category_id": 1, "name": "Lambrusco Grasparossa"},
            {"id": 1078, "main_category_id": 1, "name": "Lambrusco Salamino"},
            {"id": 1079, "main_category_id": 1, "name": "Loureiro"},
            {"id": 1080, "main_category_id": 1, "name": "Malbec"},
            {"id": 1081, "main_category_id": 1, "name": "Malbo Gentile"},
            {"id": 1082, "main_category_id": 1, "name": "Malvasia"},
            {"id": 1083, "main_category_id": 1, "name": "Malvasia Fina"},
            {"id": 1084, "main_category_id": 1, "name": "Malvasia Preta"},
            {"id": 1085, "main_category_id": 1, "name": "Malvasia Rei"},
            {"id": 1086, "main_category_id": 1, "name": "Manteúdo"},
            {"id": 1087, "main_category_id": 1, "name": "Maria Gomes"},
            {"id": 1088, "main_category_id": 1, "name": "Marsanne"},
            {"id": 1089, "main_category_id": 1, "name": "Marufo"},
            {"id": 1090, "main_category_id": 1, "name": "Mazuelo"},
            {"id": 1091, "main_category_id": 1, "name": "Merlot"},
            {"id": 1092, "main_category_id": 1, "name": "Molinara"},
            {"id": 1093, "main_category_id": 1, "name": "Moreto"},
            {"id": 1094, "main_category_id": 1, "name": "Moscatel"},
            {"id": 1095, "main_category_id": 1, "name": "Moscatel Galego"},
            {"id": 1096, "main_category_id": 1, "name": "Moscatel Graúdo"},
            {"id": 1097, "main_category_id": 1, "name": "Moscatel Roxo"},
            {"id": 1098, "main_category_id": 1, "name": "Moscato Reale"},
            {"id": 1099, "main_category_id": 1, "name": "Mourisco"},
            {"id": 1100, "main_category_id": 1, "name": "Nebbiolo"},
            {"id": 1101, "main_category_id": 1, "name": "Negra-Mole"},
            {"id": 1102, "main_category_id": 1, "name": "Nerello Mascalese"},
            {"id": 1103, "main_category_id": 1, "name": "Nero d’Avola"},
            {"id": 1104, "main_category_id": 1, "name": "Nevoeira"},
            {"id": 1105, "main_category_id": 1, "name": "Olho de Lebre"},
            {"id": 1106, "main_category_id": 1, "name": "Oseleta"},
            {"id": 1107, "main_category_id": 1, "name": "Palomino"},
            {"id": 1108, "main_category_id": 1, "name": "Perrum"},
            {"id": 1109, "main_category_id": 1, "name": "Petit Manseng"},
            {"id": 1110, "main_category_id": 1, "name": "Petit Verdot"},
            {"id": 1111, "main_category_id": 1, "name": "Petite Syrah"},
            {"id": 1112, "main_category_id": 1, "name": "Pinot Blanc"},
            {"id": 1113, "main_category_id": 1, "name": "Pinot Grigio"},
            {"id": 1114, "main_category_id": 1, "name": "Pinot Meunier"},
            {"id": 1115, "main_category_id": 1, "name": "Pinot Noir"},
            {"id": 1116, "main_category_id": 1, "name": "Pinotage"},
            {"id": 1117, "main_category_id": 1, "name": "Português Azul"},
            {"id": 1118, "main_category_id": 1, "name": "Preto Martinho"},
            {"id": 1119, "main_category_id": 1, "name": "Primitivo"},
            {"id": 1120, "main_category_id": 1, "name": "Procanico"},
            {"id": 1121, "main_category_id": 1, "name": "Rabigato"},
            {"id": 1122, "main_category_id": 1, "name": "Rabo de Ovelha"},
            {"id": 1123, "main_category_id": 1, "name": "Ramisco"},
            {"id": 1124, "main_category_id": 1, "name": "Riesling"},
            {"id": 1125, "main_category_id": 1, "name": "Rolle"},
            {"id": 1126, "main_category_id": 1, "name": "Rondinella"},
            {"id": 1127, "main_category_id": 1, "name": "Roupeiro"},
            {"id": 1128, "main_category_id": 1, "name": "Roussanne"},
            {"id": 1129, "main_category_id": 1, "name": "Rufete"},
            {"id": 1130, "main_category_id": 1, "name": "Sangiovese"},
            {"id": 1131, "main_category_id": 1, "name": "Sangiovese Grosso"},
            {"id": 1132, "main_category_id": 1, "name": "Sauvignon Blanc"},
            {"id": 1133, "main_category_id": 1, "name": "Sercial"},
            {"id": 1134, "main_category_id": 1, "name": "Sercialinho"},
            {"id": 1135, "main_category_id": 1, "name": "Sousão"},
            {"id": 1136, "main_category_id": 1, "name": "Sylvaner"},
            {"id": 1137, "main_category_id": 1, "name": "Syrah"},
            {"id": 1138, "main_category_id": 1, "name": "Száraz"},
            {"id": 1139, "main_category_id": 1, "name": "Sárgamuskotály"},
            {"id": 1140, "main_category_id": 1, "name": "Sémillon"},
            {"id": 1141, "main_category_id": 1, "name": "Síria"},
            {"id": 1142, "main_category_id": 1, "name": "Tannat"},
            {"id": 1143, "main_category_id": 1, "name": "Tempranillo"},
            {"id": 1144, "main_category_id": 1, "name": "Terrantez"},
            {"id": 1145, "main_category_id": 1, "name": "Terrantez do Pico"},
            {"id": 1146, "main_category_id": 1, "name": "Tibouren"},
            {"id": 1147, "main_category_id": 1, "name": "Tinta Amarela"},
            {"id": 1148, "main_category_id": 1, "name": "Tinta Barroca"},
            {"id": 1149, "main_category_id": 1, "name": "Tinta Caiada"},
            {"id": 1150, "main_category_id": 1, "name": "Tinta Carvalha"},
            {"id": 1151, "main_category_id": 1, "name": "Tinta da Barca"},
            {"id": 1152, "main_category_id": 1, "name": "Tinta de Toro"},
            {"id": 1153, "main_category_id": 1, "name": "Tinta Francisca"},
            {"id": 1154, "main_category_id": 1, "name": "Tinta Grossa"},
            {"id": 1155, "main_category_id": 1, "name": "Tinta Miúda"},
            {"id": 1156, "main_category_id": 1, "name": "Tinta Negra"},
            {"id": 1157, "main_category_id": 1, "name": "Tinta Pinheira"},
            {"id": 1158, "main_category_id": 1, "name": "Tinta Pomar"},
            {"id": 1159, "main_category_id": 1, "name": "Tinta Roriz"},
            {"id": 1160, "main_category_id": 1, "name": "Tinto Cão"},
            {"id": 1161, "main_category_id": 1, "name": "Touriga Franca"},
            {"id": 1162, "main_category_id": 1, "name": "Touriga Fêmea"},
            {"id": 1163, "main_category_id": 1, "name": "Touriga Nacional"},
            {"id": 1164, "main_category_id": 1, "name": "Trajadura"},
            {"id": 1165, "main_category_id": 1, "name": "Trebbiano"},
            {"id": 1166, "main_category_id": 1, "name": "Trincadeira"},
            {"id": 1167, "main_category_id": 1, "name": "Trincadeira das Pratas"},
            {"id": 1168, "main_category_id": 1, "name": "Uva-Cão"},
            {"id": 1169, "main_category_id": 1, "name": "Verdelho"},
            {"id": 1170, "main_category_id": 1, "name": "Verdelho dos Açores"},
            {"id": 1171, "main_category_id": 1, "name": "Vermentino"},
            {"id": 1172, "main_category_id": 1, "name": "Vidal"},
            {"id": 1173, "main_category_id": 1, "name": "Vinhão"},
            {"id": 1174, "main_category_id": 1, "name": "Viognier"},
            {"id": 1175, "main_category_id": 1, "name": "Viosinho"},
            {"id": 1176, "main_category_id": 1, "name": "Vital"},
            {"id": 1177, "main_category_id": 1, "name": "Viura"},
            {"id": 1178, "main_category_id": 1, "name": "Zéta"},

            # Category: Generosos
            {"id": 4001, "main_category_id": 4, "name": "Alicante Bouschet"},
            {"id": 4002, "main_category_id": 4, "name": "Alvarinho"},
            {"id": 4003, "main_category_id": 4, "name": "Aragonês"},
            {"id": 4004, "main_category_id": 4, "name": "Arinto"},
            {"id": 4005, "main_category_id": 4, "name": "Bastardo"},
            {"id": 4006, "main_category_id": 4, "name": "Boal"},
            {"id": 4007, "main_category_id": 4, "name": "Fernão Pires"},
            {"id": 4008, "main_category_id": 4, "name": "Malmsey"},
            {"id": 4009, "main_category_id": 4, "name": "Malvasia"},
            {"id": 4010, "main_category_id": 4, "name": "Malvasia-Cândida"},
            {"id": 4011, "main_category_id": 4, "name": "Marufo"},
            {"id": 4012, "main_category_id": 4, "name": "Merlot"},
            {"id": 4013, "main_category_id": 4, "name": "Moscatel"},
            {"id": 4014, "main_category_id": 4, "name": "Moscatel Galego"},
            {"id": 4015, "main_category_id": 4, "name": "Moscatel Galego Dourado"},
            {"id": 4016, "main_category_id": 4, "name": "Moscatel Graúdo"},
            {"id": 4017, "main_category_id": 4, "name": "Moscatel Roxo"},
            {"id": 4018, "main_category_id": 4, "name": "Sercial"},
            {"id": 4019, "main_category_id": 4, "name": "Terrantez"},
            {"id": 4020, "main_category_id": 4, "name": "Tinta Negra"},
            {"id": 4021, "main_category_id": 4, "name": "Touriga Nacional"},
            {"id": 4022, "main_category_id": 4, "name": "Verdelho"},
        ]

        for variety in varieties:
            yield variety
