global:
  sendAnonymousUsage: false
  checkNewVersion: false

api:
  insecure: false
  dashboard: true
  debug: true

pilot:
  dashboard: true

log:
  level: DEBUG
  # filePath: "/var/log/log-file.log"

# accessLog:
#  filePath: "/var/log/log-access.log"
#  bufferingSize: 100

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false
    watch: true
    swarmMode: false

  file:
    directory: "/etc/traefik/dynamic"
    watch: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

certificatesResolvers:
  # letsencrypt:
  le:
    acme:
      email: robccsilva@gmail.com
#      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      caServer: https://acme-v02.api.letsencrypt.org/directory
      storage: ./acme.json
      keyType: EC256
      httpChallenge:
        entryPoint: web


#      - --entrypoints.web.address=:80
#      - --entrypoints.websecure.address=:443
#      - --providers.docker=true
#      - --providers.docker.exposedByDefault=false
#      - --api
#      - --certificatesresolvers.le.acme.email=${TRAEFIK_SSLEMAIL?Variable not set}
#      - --certificatesresolvers.le.acme.storage=./acme.json
#      - --certificatesresolvers.le.acme.tlschallenge=true
#      - --log.level=DEBUG