---
http:
  routers:
    traefik:
      entryPoints:
      - websecure
      middlewares:
      - authentification

      service: api@internal
      rule: "Host(`${DOMAIN_VHOST_BOARD}`)"
      tls:
        # certResolver: letsencrypt
        certresolver: le

    rtdomainapiserverdev:
      entryPoints:
      - websecure
      middlewares:
      - security
      - compression
      service: svc-apiserver
      rule: Host (`${DOMAIN_VHOST_API}`)
      tls:
        # certResolver: letsencrypt
        certresolver: le
        domains:
          - main: "${DOMAIN_VHOST_API}"
            sans:
              - "${DOMAIN_VHOST_API}"

    rtdomainwebserverdev:
      entryPoints:
      - websecure
      middlewares:
      - security
      - compression
      service: svc-webserver
      rule: Host (`${DOMAIN_VHOST_WEB}`)
      tls:
        # certResolver: letsencrypt
        certresolver: le
        domains:
          - main: "${DOMAIN_VHOST_WEB}"
            sans:
              - "${DOMAIN_VHOST_WEB}"

    rtdomainappserverdev:
      entryPoints:
      - websecure
      middlewares:
      - security
      - compression
      service: svc-appserver
      rule: Host (`${DOMAIN_VHOST_APP}`)
      tls:
        # certResolver: letsencrypt
        certresolver: le
        domains:
          - main: "${DOMAIN_VHOST_APP}"
            sans:
              - "${DOMAIN_VHOST_APP}"
