---
http:
  services:
    svc-apiserver:
      loadBalancer:
        servers:
        - url: "${API_SERVER_URL}"

    svc-webserver:
      loadBalancer:
        servers:
        - url: "${WEB_SERVER_URL}"

    svc-appserver:
      loadBalancer:
        servers:
        - url: "${APP_SERVER_URL}"
