# running docker-compose has requirements => make server.network
# docker network create netpublic
# docker-compose build --no-cache --pull && docker-compose up --force-recreate

version: "3.9"
services:
  traefik:
    image: traefik:${TRAEFIK_VERSION}
    env_file: .env
    ports:
      - 80:80
      - 443:443
    hostname: traefik
    container_name: traefik
    environment:
      - DOMAIN_VHOST_ROOT=${DOMAIN_VHOST_ROOT}
      - DOMAIN_VHOST_BOARD=${DOMAIN_VHOST_BOARD}
      - DOMAIN_VHOST_WEB=${DOMAIN_VHOST_WEB}
      - DOMAIN_VHOST_API=${DOMAIN_VHOST_API}
      - DOMAIN_VHOST_APP=${DOMAIN_VHOST_APP}
      - TRAEFIK_SSLEMAIL=${TRAEFIK_SSLEMAIL}
      - TRAEFIK_BASIC_AUTH_USER_PASSWORD=${TRAEFIK_BASIC_AUTH_USER_PASSWORD}
      - TZ=${TIMEZONE}
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker
      # Do not expose containers unless explicitly told so
      - --providers.docker.exposedByDefault=false
      - --api
      - --certificatesresolvers.le.acme.email=${TRAEFIK_SSLEMAIL?Variable not set}
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
      # - "--certificatesresolvers.le.acme.caserver=https://acme-staging-v02.api.le.org/directory"
      - "--certificatesResolvers.le.acme.tlschallenge=true"
      - "--accesslog=true"
      - "--log.level=DEBUG"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - letsencrypt:/letsencrypt
    labels:
      - "traefik.enable=true"
      - --log.level=DEBUG
      #- --log.filepath=/var/log/traefik.log
      - --accesslog=true
      #- --accesslog.filepath=/var/log/traefik-access.log
      - --providers.docker.network=netpublic
      # Dashboard
      - "traefik.http.routers.traefik.rule=Host(`${DOMAIN_VHOST_BOARD}`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=le"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.middlewares=authtraefik"
      - "traefik.http.middlewares.authtraefik.basicauth.users=${TRAEFIK_BASIC_AUTH_USER_PASSWORD}"
      # global redirect to https
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      # middleware redirect
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    restart: unless-stopped
    networks:
      - netpublic

  apiserver:
    hostname: apiserver
    container_name: apiserver
    env_file: .env
    build:
      context: backend
      args:
        - PYTHON_VERSION=${PYTHON_VERSION}
      dockerfile: dockerfile-apiserver-prod
    # PROD does not mount volumes, it copies everything to container
    #working_dir: /app
    #volumes:
    #  - ./backend:/app
    ports:
      - ${API_SERVER_PORT_EXTERNAL}:${API_SERVER_PORT_INTERNAL}
    environment:
      - FLASK_APP=${FLASK_APP}
      - FLASK_DEBUG=${FLASK_DEBUG}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - SERVICE_LOG=${SERVICE_LOG}
      - APPLICATION_HOST=${APPLICATION_HOST}
      - APPLICATION_PORT=${APPLICATION_PORT}
      - DOMAIN_VHOST_ROOT=${DOMAIN_VHOST_ROOT}
      - DOMAIN_VHOST_BOARD=${DOMAIN_VHOST_BOARD}
      - DOMAIN_VHOST_WEB=${DOMAIN_VHOST_WEB}
      - DOMAIN_VHOST_API=${DOMAIN_VHOST_API}
      - DOMAIN_VHOST_APP=${DOMAIN_VHOST_APP}
      - TZ=${TIMEZONE}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.apiserver.rule=Host(`${DOMAIN_VHOST_API}`)"
      - "traefik.http.routers.apiserver.entrypoints=websecure"
      - "traefik.http.routers.apiserver.tls=true"
      - "traefik.http.routers.apiserver.tls.certresolver=le"
      - "traefik.http.routers.apiserver.tls.domains[0].main=${DOMAIN_VHOST_API}"
      - "traefik.http.services.apiserver.loadbalancer.server.port=${API_SERVER_PORT_INTERNAL}"
    command: flask run --host 0.0.0.0 --port ${API_SERVER_PORT_INTERNAL} --debugger --with-threads
    networks:
      - netpublic

  vhostwww:
    build:
      context: frontend/www
      args:
        - NODE_VERSION=${NODE_VERSION}
      dockerfile: dockerfile-vhostwww-dev
    env_file: .env
    #environment:
    #- NODE_ENV="development"
    # The base node image sets a very verbose log level. => ENV NPM_CONFIG_LOGLEVEL warn
    #- NPM_CONFIG_LOGLEVEL warn
    ports:
      - "${WEB_SERVER_PORT_EXTERNAL}:${WEB_SERVER_PORT_INTERNAL}"
      - "${WEB_HMR_SERVER_PORT_EXTERNAL}:${WEB_HMR_SERVER_PORT_INTERNAL}"
    volumes:
      - "./frontend/www:/app"
    labels:
      #- "traefik.enable=true"
      #- "traefik.http.routers.vhostwww.rule=Host(`${DOMAIN_VHOST_WEB}`)"
      #- "traefik.http.routers.vhostwww.entrypoints=websecure"
      #- "traefik.http.routers.vhostwww.tls=true"
      #- "traefik.http.routers.vhostwww.tls.certresolver=le"
      #- "traefik.http.routers.vhostwww.tls.domains[0].main=${DOMAIN_VHOST_WEB}"
      #- "traefik.http.services.vhostwww.loadbalancer.server.port=${WEB_SERVER_PORT_INTERNAL}"
      # global redirect to https
      #- "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      #- "traefik.http.routers.http-catchall.entrypoints=web"
      #- "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      # middleware redirect
      #- "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

      - "traefik.enable=true"
      - "traefik.http.routers.vhostwww.rule=Host(`${DOMAIN_VHOST_ROOT}`) || Host(`${DOMAIN_VHOST_WEB}`)"
      - "traefik.http.routers.vhostwww.entrypoints=web"
      - "traefik.http.routers.vhostwww.middlewares=redirect-to-https@docker"
      - "traefik.http.routers.vhostwww-secure.rule=Host(`${DOMAIN_VHOST_ROOT}`) || Host(`${DOMAIN_VHOST_WEB}`)"
      - "traefik.http.routers.vhostwww-secure.entrypoints=websecure"
      - "traefik.http.routers.vhostwww-secure.tls.certresolver=le"
      - "traefik.http.middlewares.redirect-to-https.redirectScheme.scheme=https"
    command: sh -c "cd /app && npm install -g pnpm && pnpm install && pnpm dev"
    # depends_on:
    #  - apiserver
    networks:
      - netpublic

networks:
  netpublic:
    external: true
  netprivate:
    external: false

volumes:
  letsencrypt:
    name: letsencrypt
