version: "2"

services:
  apiserver:
    hostname: apiserver
    env_file:
      - .env
    # image: python:3.7.16-slim
    build:
      context: .
      dockerfile: dockerfile-apiserver
    # working_dir: /mnt
    working_dir: /app
    volumes:
      # - .:/mnt
      - .:/app
#    depends_on:
#      - db
    ports:
      - 3000:3000
    # command: python src/server.py

  nginx:
    hostname: nginx
    # image: webapp-nginx
    build:
      context: .
      dockerfile: dockerfile-nginx
    ports:
      - 8080:80
    depends_on:
      - apiserver

  dbdata:
    image: busybox
    volumes:
#     - /var/lib/postgresql/data
      - /var/lib/mysql/data
#  db:
#    image: postgres:9.4
#    volumes_from:
#      - dbdata

  testserver:
    env_file: .env
    image: python:3.7.16-slim
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - testdb
    ports:
      - 5053:5053
    environment:
      APPLICATION_PORT: 5053
      APPLICATION_DB_CONTAINER: testdb
    command: python -m pytest test/

  testdb:
#   image: postgres:9.4
    image: oraclelinux:8-slim
