version: "3.4"
services:
  db:
    image: mariadb:10.6.11
    volumes:
      - ./data/mariadb:/var/lib/mysql
    env_file: .env
  app:
    build:
      context: backend
      dockerfile: Dockerfile.local
    command: tail -f /dev/null
    env_file: .env
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
    depends_on:
      - db