---
http:
  routers:
    traefik:
      entryPoints:
      - websecure
      middlewares:
      - authentification

      service: api@internal
      rule: "Host(`${DOMAIN_VHOST_BOARD}`)"
      tls:
        # certResolver: letsencrypt
        certresolver: le

    rtdomainapiserverdev:
      entryPoints:
      - websecure
      middlewares:
      - security
      - compression
      service: svc-apiserver
      rule: Host (`${DOMAIN_VHOST_API_DEV}`)
      tls:
        # certResolver: letsencrypt
        certresolver: le
        domains:
          - main: "${DOMAIN_VHOST_API_DEV}"
            sans:
              - "${DOMAIN_VHOST_API_DEV}"

    rtdomainwebserverdev:
      entryPoints:
      - websecure
      middlewares:
      - security
      - compression
      service: svc-webserver
      rule: Host (`${DOMAIN_VHOST_WWW_DEV}`)
      tls:
        # certResolver: letsencrypt
        certresolver: le
        domains:
          - main: "${DOMAIN_VHOST_WWW_DEV}"
            sans:
              - "${DOMAIN_VHOST_WWW_DEV}"

    rtdomainappserverdev:
      entryPoints:
      - websecure
      middlewares:
      - security
      - compression
      service: svc-appserver
      rule: Host (`${DOMAIN_VHOST_APP_DEV}`)
      tls:
        # certResolver: letsencrypt
        certresolver: le
        domains:
          - main: "${DOMAIN_VHOST_APP_DEV}"
            sans:
              - "${DOMAIN_VHOST_APP_DEV}"
