"""empty message

Revision ID: 9c1b783ff051
Revises: 51e2c29ad95
Create Date: 2022-12-26 18:56:01.850964

"""

# revision identifiers, used by Alembic.
revision = '9c1b783ff051'
down_revision = '51e2c29ad95'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
