"""Add user changes

Revision ID: c7a0be55e5ff
Revises: e44c14cc48c3
Create Date: 2023-05-22 13:50:06.781992

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "c7a0be55e5ff"
down_revision = "e44c14cc48c3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "email", sa.String(length=50), nullable=False, comment="Email"
            )
        )
        batch_op.alter_column(
            "first_name",
            existing_type=mysql.VARCHAR(length=150),
            nullable=True,
            existing_comment="First name",
        )
        batch_op.alter_column(
            "middle_name",
            existing_type=mysql.VARCHAR(length=150),
            nullable=True,
            existing_comment="Middle name",
        )
        batch_op.alter_column(
            "last_name",
            existing_type=mysql.VARCHAR(length=150),
            nullable=True,
            existing_comment="Last name",
        )
        batch_op.create_unique_constraint(None, ["email"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.alter_column(
            "last_name",
            existing_type=mysql.VARCHAR(length=150),
            nullable=False,
            existing_comment="Last name",
        )
        batch_op.alter_column(
            "middle_name",
            existing_type=mysql.VARCHAR(length=150),
            nullable=False,
            existing_comment="Middle name",
        )
        batch_op.alter_column(
            "first_name",
            existing_type=mysql.VARCHAR(length=150),
            nullable=False,
            existing_comment="First name",
        )
        batch_op.drop_column("email")

    # ### end Alembic commands ###
