"""Change wine region country data type

Revision ID: 503193dd9c54
Revises: 120e93fa776a
Create Date: 2023-05-31 17:12:07.425564

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "503193dd9c54"
down_revision = "120e93fa776a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("region", schema=None) as batch_op:
        batch_op.alter_column(
            "country",
            existing_type=mysql.BIGINT(display_width=20),
            type_=sa.String(length=2),
            existing_comment="Country",
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("region", schema=None) as batch_op:
        batch_op.alter_column(
            "country",
            existing_type=sa.String(length=2),
            type_=mysql.BIGINT(display_width=20),
            existing_comment="Country",
            existing_nullable=False,
        )

    # ### end Alembic commands ###
