"""Change table verifications

Revision ID: dfc569cc1c53
Revises: 6f3d0af8948a
Create Date: 2023-07-01 23:02:38.774052

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "dfc569cc1c53"
down_revision = "6f3d0af8948a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("verification", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "type",
                sa.Enum("user", "email", "otp", name="lowercase_enum"),
                nullable=False,
                comment="Verification type (e.g. user,email,otp)",
            )
        )
        batch_op.alter_column(
            "date_created",
            existing_type=mysql.DATETIME(),
            type_=sa.TIMESTAMP(),
            nullable=False,
            comment="Timestamp with token date creation",
            existing_comment="Date when token was created",
        )
        batch_op.drop_index("ad_user_action_token")
        batch_op.create_unique_constraint(
            "ad_user_type_token", ["user_id", "type", "token"]
        )
        batch_op.create_index(
            batch_op.f("ix_verification_date_created"),
            ["date_created"],
            unique=False,
        )
        batch_op.drop_column("action")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("verification", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "action",
                mysql.VARCHAR(length=10),
                nullable=False,
                comment="Verification action e.g. user",
            )
        )
        batch_op.drop_index(batch_op.f("ix_verification_date_created"))
        batch_op.drop_constraint("ad_user_type_token", type_="unique")
        batch_op.create_index(
            "ad_user_action_token",
            ["user_id", "action", "token"],
            unique=False,
        )
        batch_op.alter_column(
            "date_created",
            existing_type=sa.TIMESTAMP(),
            type_=mysql.DATETIME(),
            nullable=True,
            comment="Date when token was created",
            existing_comment="Timestamp with token date creation",
        )
        batch_op.drop_column("type")

    # ### end Alembic commands ###
