"""Add user account id

Revision ID: 7b410129092e
Revises: c7a0be55e5ff
Create Date: 2023-05-22 14:27:26.636578

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7b410129092e"
down_revision = "c7a0be55e5ff"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "account_id",
                sa.BigInteger(),
                nullable=False,
                comment="Account id",
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("account_id")

    # ### end Alembic commands ###
