"""Change store fields nullable to true

Revision ID: df1289079e2d
Revises: 84228070dae4
Create Date: 2023-05-22 20:32:35.146545

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "df1289079e2d"
down_revision = "84228070dae4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("store", schema=None) as batch_op:
        batch_op.alter_column(
            "store_name",
            existing_type=mysql.VARCHAR(length=50),
            nullable=True,
            existing_comment="Store name",
        )
        batch_op.alter_column(
            "gps_latitude",
            existing_type=mysql.VARCHAR(length=25),
            nullable=True,
            existing_comment="GPS coordinates, latitude",
        )
        batch_op.alter_column(
            "gps_longitude",
            existing_type=mysql.VARCHAR(length=25),
            nullable=True,
            existing_comment="GPS coordinates, longitude",
        )
        batch_op.alter_column(
            "contact_email",
            existing_type=mysql.VARCHAR(length=50),
            nullable=True,
            existing_comment="Email",
        )
        batch_op.alter_column(
            "contact_phone",
            existing_type=mysql.VARCHAR(length=50),
            nullable=True,
            existing_comment="Phone",
        )
        batch_op.alter_column(
            "contact_phone_description",
            existing_type=mysql.VARCHAR(length=50),
            nullable=True,
            existing_comment="Phone description (e.g. call to land line)",
        )
        batch_op.alter_column(
            "contact_phone_secondary",
            existing_type=mysql.VARCHAR(length=50),
            nullable=True,
            existing_comment="Secondary phone",
        )
        batch_op.alter_column(
            "contact_phone_secondary_description",
            existing_type=mysql.VARCHAR(length=50),
            nullable=True,
            existing_comment="Secondary phone description (e.g. mobile phone)",
        )
        batch_op.alter_column(
            "schedule",
            existing_type=mysql.VARCHAR(length=50),
            nullable=True,
            existing_comment="Open hours (e.g. Open 8h to 24h, Mon to Sat)",
        )
        batch_op.alter_column(
            "social_facebook",
            existing_type=mysql.VARCHAR(length=50),
            nullable=True,
            existing_comment="Address for social network Facebook",
        )
        batch_op.alter_column(
            "social_twitter",
            existing_type=mysql.VARCHAR(length=50),
            nullable=True,
            existing_comment="Address for social network Twitter",
        )
        batch_op.alter_column(
            "social_instagram",
            existing_type=mysql.VARCHAR(length=50),
            nullable=True,
            existing_comment="Address for social network Instagram",
        )
        batch_op.alter_column(
            "social_tiktok",
            existing_type=mysql.VARCHAR(length=50),
            nullable=True,
            existing_comment="Address for social network Tiktok",
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("store", schema=None) as batch_op:
        batch_op.alter_column(
            "social_tiktok",
            existing_type=mysql.VARCHAR(length=50),
            nullable=False,
            existing_comment="Address for social network Tiktok",
        )
        batch_op.alter_column(
            "social_instagram",
            existing_type=mysql.VARCHAR(length=50),
            nullable=False,
            existing_comment="Address for social network Instagram",
        )
        batch_op.alter_column(
            "social_twitter",
            existing_type=mysql.VARCHAR(length=50),
            nullable=False,
            existing_comment="Address for social network Twitter",
        )
        batch_op.alter_column(
            "social_facebook",
            existing_type=mysql.VARCHAR(length=50),
            nullable=False,
            existing_comment="Address for social network Facebook",
        )
        batch_op.alter_column(
            "schedule",
            existing_type=mysql.VARCHAR(length=50),
            nullable=False,
            existing_comment="Open hours (e.g. Open 8h to 24h, Mon to Sat)",
        )
        batch_op.alter_column(
            "contact_phone_secondary_description",
            existing_type=mysql.VARCHAR(length=50),
            nullable=False,
            existing_comment="Secondary phone description (e.g. mobile phone)",
        )
        batch_op.alter_column(
            "contact_phone_secondary",
            existing_type=mysql.VARCHAR(length=50),
            nullable=False,
            existing_comment="Secondary phone",
        )
        batch_op.alter_column(
            "contact_phone_description",
            existing_type=mysql.VARCHAR(length=50),
            nullable=False,
            existing_comment="Phone description (e.g. call to land line)",
        )
        batch_op.alter_column(
            "contact_phone",
            existing_type=mysql.VARCHAR(length=50),
            nullable=False,
            existing_comment="Phone",
        )
        batch_op.alter_column(
            "contact_email",
            existing_type=mysql.VARCHAR(length=50),
            nullable=False,
            existing_comment="Email",
        )
        batch_op.alter_column(
            "gps_longitude",
            existing_type=mysql.VARCHAR(length=25),
            nullable=False,
            existing_comment="GPS coordinates, longitude",
        )
        batch_op.alter_column(
            "gps_latitude",
            existing_type=mysql.VARCHAR(length=25),
            nullable=False,
            existing_comment="GPS coordinates, latitude",
        )
        batch_op.alter_column(
            "store_name",
            existing_type=mysql.VARCHAR(length=50),
            nullable=False,
            existing_comment="Store name",
        )

    # ### end Alembic commands ###
