"""Change store address id to be not mandatory

Revision ID: fc740c082996
Revises: f63fbdc52047
Create Date: 2023-06-16 16:11:41.039894

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "fc740c082996"
down_revision = "f63fbdc52047"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("alembic_version_")
    with op.batch_alter_table("account", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "user_id",
                sa.BigInteger(),
                nullable=True,
                comment="Administrator user of the account",
            )
        )

    with op.batch_alter_table("store", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=mysql.BIGINT(display_width=20),
            comment="Primary key",
            existing_nullable=False,
            autoincrement=True,
        )
        batch_op.alter_column(
            "address_id",
            existing_type=mysql.BIGINT(display_width=20),
            nullable=True,
            existing_comment="Address id",
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("store", schema=None) as batch_op:
        batch_op.alter_column(
            "address_id",
            existing_type=mysql.BIGINT(display_width=20),
            nullable=False,
            existing_comment="Address id",
        )
        batch_op.alter_column(
            "id",
            existing_type=mysql.BIGINT(display_width=20),
            comment=None,
            existing_comment="Primary key",
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("account", schema=None) as batch_op:
        batch_op.drop_column("user_id")

    op.create_table(
        "alembic_version_",
        sa.Column("version_num", mysql.VARCHAR(length=32), nullable=False),
        sa.PrimaryKeyConstraint("version_num"),
        mysql_collate="utf8mb4_general_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
