"""Add store field account_id

Revision ID: 84228070dae4
Revises: 7b410129092e
Create Date: 2023-05-22 20:24:29.480257

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "84228070dae4"
down_revision = "7b410129092e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("store", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "account_id",
                sa.Integer(),
                nullable=False,
                comment="Account id",
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("store", schema=None) as batch_op:
        batch_op.drop_column("account_id")

    # ### end Alembic commands ###
