"""Add unique constraint to Ad model

Revision ID: ae8af0d455e0
Revises: 4405d1889a99
Create Date: 2023-05-18 16:03:13.658258

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ae8af0d455e0'
down_revision = '4405d1889a99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_index('title')
        batch_op.create_unique_constraint('uq_id_title', ['id', 'title'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads', schema=None) as batch_op:
        batch_op.drop_constraint('uq_id_title', type_='unique')
        batch_op.create_index('title', ['title'], unique=False)
        batch_op.alter_column('uuid',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
