"""Accounts - Make account name unique

Revision ID: f63fbdc52047
Revises: 503193dd9c54
Create Date: 2023-06-13 16:15:30.261728

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f63fbdc52047'
down_revision = '503193dd9c54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20),
               comment='Primary key',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('account_name',
               existing_type=mysql.VARCHAR(length=60),
               nullable=False,
               comment='Account name is unique',
               existing_comment='Account can have any name, it is an internal reference')
        batch_op.create_unique_constraint(None, ['account_name'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20),
               comment='Primary key',
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20),
               comment=None,
               existing_comment='Primary key',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('account_name',
               existing_type=mysql.VARCHAR(length=60),
               nullable=True,
               comment='Account can have any name, it is an internal reference',
               existing_comment='Account name is unique')
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20),
               comment=None,
               existing_comment='Primary key',
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
