"""Change grape variety field name

Revision ID: 8f8057aaee5b
Revises: 4881073b3e24
Create Date: 2023-05-29 12:42:36.789247

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "8f8057aaee5b"
down_revision = "4881073b3e24"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("grape_variety", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "name",
                sa.String(length=50),
                nullable=True,
                comment="Name of grape variety",
            )
        )
        batch_op.drop_column("grape_variety")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("grape_variety", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "grape_variety",
                mysql.VARCHAR(length=50),
                nullable=True,
                comment="Grape variety",
            )
        )
        batch_op.drop_column("name")

    # ### end Alembic commands ###
