"""change uuid field length

Revision ID: 466dfe88c9b4
Revises: ae8af0d455e0
Create Date: 2023-05-18 17:34:05.702695

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '466dfe88c9b4'
down_revision = 'ae8af0d455e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=36),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=sa.String(length=36),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
