"""Change grape variety field name

Revision ID: 120e93fa776a
Revises: 8f8057aaee5b
Create Date: 2023-05-31 16:53:31.652744

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "120e93fa776a"
down_revision = "8f8057aaee5b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category",
        sa.Column(
            "id", sa.BigInteger(), nullable=False, comment="Primary key"
        ),
        sa.Column(
            "main_category_id",
            sa.BigInteger(),
            nullable=False,
            comment="Main category id",
        ),
        sa.Column(
            "name",
            sa.String(length=50),
            nullable=True,
            comment="Category name",
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_general_ci",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "region",
        sa.Column(
            "id", sa.BigInteger(), nullable=False, comment="Primary key"
        ),
        sa.Column(
            "country", sa.BigInteger(), nullable=False, comment="Country"
        ),
        sa.Column(
            "name",
            sa.String(length=50),
            nullable=True,
            comment="Name of region",
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_general_ci",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "wine_grape_variety",
        sa.Column(
            "id", sa.BigInteger(), nullable=False, comment="Primary key"
        ),
        sa.Column(
            "main_category_id",
            sa.BigInteger(),
            nullable=False,
            comment="Main category id",
        ),
        sa.Column(
            "name",
            sa.String(length=50),
            nullable=True,
            comment="Name of grape variety",
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_general_ci",
        mysql_engine="InnoDB",
    )
    op.drop_table("grape_variety")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "grape_variety",
        sa.Column(
            "id",
            mysql.BIGINT(display_width=20),
            autoincrement=True,
            nullable=False,
            comment="Primary key",
        ),
        sa.Column(
            "name",
            mysql.VARCHAR(length=50),
            nullable=True,
            comment="Name of grape variety",
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_general_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.drop_table("wine_grape_variety")
    op.drop_table("region")
    op.drop_table("category")
    # ### end Alembic commands ###
