"""Change store field account_id to remove the default value

Revision ID: f76c9e44ee48
Revises: df1289079e2d
Create Date: 2023-05-23 10:13:18.671520

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "f76c9e44ee48"
down_revision = "df1289079e2d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("store", schema=None) as batch_op:
        batch_op.alter_column(
            "account_id",
            existing_type=mysql.INTEGER(display_width=11),
            type_=sa.BigInteger(),
            existing_comment="Account id",
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("store", schema=None) as batch_op:
        batch_op.alter_column(
            "account_id",
            existing_type=sa.BigInteger(),
            type_=mysql.INTEGER(display_width=11),
            existing_comment="Account id",
            existing_nullable=False,
        )

    # ### end Alembic commands ###
