"""empty message

Revision ID: 4405d1889a99
Revises: 6ecca4fcf65f
Create Date: 2023-02-05 21:58:55.158981

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "4405d1889a99"
down_revision = "6ecca4fcf65f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ads", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.BigInteger(), nullable=False))
        batch_op.alter_column(
            "uuid", existing_type=mysql.VARCHAR(length=50), nullable=True
        )
        batch_op.create_unique_constraint(None, ["title"])
        batch_op.create_unique_constraint(None, ["uuid"])
        batch_op.create_foreign_key(None, "users", ["user_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ads", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_constraint(None, type_="unique")
        batch_op.alter_column(
            "uuid", existing_type=mysql.VARCHAR(length=50), nullable=False
        )
        batch_op.drop_column("user_id")

    # ### end Alembic commands ###
