name: Code Quality

on: [ push, pull_request ]

jobs:

  test:
    runs-on: ubuntu-latest
    
    container:
      image: paketobuildpacks/poetry-run
      
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'

      #- name: Install Poetry
      #  uses: snok/install-poetry@v1

      - name: Install Dependencies
        working-directory: ./backend
        run: poetry install
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Black
        working-directory: ./backend
        run: poetry run black . --check

      - name: Isort
        working-directory: ./backend
        run: poetry run isort . --check-only --profile black

      - name: Run tests and generate coverage
        working-directory: ./backend
        run: poetry run pytest -vv --cov=api tests/

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
