name: Deploy to Server

on:
  push:
    branches:
      - develop
      - main

jobs:
  deploy-develop:
    name: DEV - Deploy environment
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - name: DEV - Transfer files to server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.WEB_SERVER_HOST }}
          username: ${{ secrets.WEB_SERVER_USERNAME }}
          password: ${{ secrets.WEB_SERVER_PASSWORD }}
          # source: ./build/*
          source: ./*
          target: ${{ secrets.WEB_SERVER_ROOT }}
      - name: DEV - Deploy
        run: sh /opt/docker/deploy-dev.sh

  deploy-production:
    name: PROD - Deploy environment
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v2
      - name: PROD - Transfer files to server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.WEB_SERVER_HOST }}
          username: ${{ secrets.WEB_SERVER_USERNAME }}
          password: ${{ secrets.WEB_SERVER_PASSWORD }}
          source: ./*
          target: ${{ secrets.WEB_SERVER_ROOT }}
