name: Deploy to Server

on:
  push:
    branches:
      - develop
      - main

jobs:
  deploy-develop:
    name: DEV - Deploy environment
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - name: Transfer files to server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.WEB_SERVER_HOST }}
          username: ${{ secrets.WEB_SERVER_USERNAME }}
          password: ${{ secrets.WEB_SERVER_PASSWORD }}
          # source: ./build/*
          source: ./*
          target: ${{ secrets.WEB_SERVER_ROOT }}
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.WEB_SERVER_HOST }}
          username: ${{ secrets.WEB_SERVER_USERNAME }}
          key: ${{ secrets.WEB_SERVER_SSH_PRIVATE_KEY }}
          port: ${{ secrets.WEB_SERVER_SSH_PORT }}
          script: sh /opt/docker/deploy-dev.sh
#      - name: Setup SSH
#        uses: webfactory/ssh-agent@v0.5.0
#        with:
#          ssh-private-key: ${{ secrets.WEB_SERVER_SSH_PRIVATE_KEY }}
#      - name: Deploy code
#        run: |
#          chmod +x /opt/docker/deploy-dev.sh
#          /opt/docker/deploy-dev.sh
#          shell: bash
        # run: ssh ${{ secrets.WEB_SERVER_USERNAME }}@${{ secrets.WEB_SERVER_HOST }} 'bash -s' < /opt/docker/deploy-dev.sh

  deploy-production:
    name: PROD - Deploy environment
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v3
      - name: PROD - Transfer files to server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.WEB_SERVER_HOST }}
          username: ${{ secrets.WEB_SERVER_USERNAME }}
          password: ${{ secrets.WEB_SERVER_PASSWORD }}
          source: ./*
          target: ${{ secrets.WEB_SERVER_ROOT }}
